# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :ubuntu do |ubuntu_config|
    ubuntu_config.vm.box = "ubuntu/xenial64"
    ubuntu_config.vm.hostname = "ubuntu"
    #ubuntu_config.vm.network :private_network, ip: "10.0.15.12"
    # ubuntu_config.vm.network "forwarded_port", guest: 8080, host: 8888
    ubuntu_config.vm.network "public_network", type: "dhcp"
      ubuntu_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    #ubuntu_config.vm.provision :shell, path: "bootstrap.sh"
  end
end
