# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :freebsd do |freebsd_config|
    freebsd_config.vm.guest = :freebsd
    freebsd_config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    freebsd_config.vm.box = "freebsd/FreeBSD-11.1-RELEASE"
    freebsd_config.vm.box_version = "2017.07.21"
    freebsd_config.vm.hostname = "freebsd"
    freebsd_config.vm.base_mac = "080027D14C66"
    freebsd_config.ssh.shell = "sh"
  # freebsd_config.vm.network :private_network, ip: "10.0.15.12"
  # freebsd_config.vm.network "forwarded_port", guest: 8080, host: 8888
      freebsd_config.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1024"]
        vb.customize ["modifyvm", :id, "--cpus", "1"]
        vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
        vb.customize ["modifyvm", :id, "--audio", "none"]
        vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
        vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      end
    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
     #freebsd_config.vm.provision "shell", inline: <<-SHELL
       #
     #SHELL
  end
end