# Defines our Vagrant environment
#
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # create ansible mgmt node
  config.vm.define :mgmt do |mgmt_config|
      mgmt_config.vm.box = "ubuntu/xenial64"
      mgmt_config.vm.hostname = "mgmt"
      mgmt_config.vm.network :private_network, ip: "10.0.15.10"
      mgmt_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
      mgmt_config.vm.provision :shell, path: "bootstrap-mgmt.sh"
  end

  #create a jenkins server
  #  config.vm.define :jenkins do |jenkins_config|
  #     #jenkins_config.vm.box = "ebracho/jenkins"
  #     jenkins_config.vm.box = "centos/7"
  #     jenkins_config.vm.hostname = "jenkins"
  #     jenkins_config.vm.network :private_network, ip: "10.0.15.12"
  #     jenkins_config.vm.network "forwarded_port", guest: 8080, host: 8888
  #     jenkins_config.vm.provider "virtualbox" do |vb|
  #       vb.memory = "1024"
  #     end
  #     jenkins_config.vm.provision :shell, path: "bootstrap-jenkins.sh"
  # end

  # create load balancer
  config.vm.define :lb do |lb_config|
      lb_config.vm.box = "ubuntu/xenial64"
      lb_config.vm.hostname = "lb"
      lb_config.vm.network :private_network, ip: "10.0.15.11"
      lb_config.vm.network "forwarded_port", guest: 80, host: 8080
      lb_config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      lb_config.vm.provision :shell, path: "bootstrap-lb.sh"
  end

  # create some web servers
  (1..2).each do |i|
    config.vm.define "web#{i}" do |node|
        node.vm.box = "ubuntu/xenial64"
        node.vm.hostname = "web#{i}"
        node.vm.network :private_network, ip: "10.0.15.2#{i}"
        node.vm.network "forwarded_port", guest: 80, host: "808#{i}"
        node.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
        end
        node.vm.provision :shell, path: "bootstrap-web.sh"
    end
  end

end
