---
- hosts: all
  become: yes
  gather_facts: no
  remote_user: ubuntu

  tasks:

  - name: install ssh key
    authorized_key: user=ubuntu 
                    key="{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}" 
                    state=present
