---
- hosts: all
  become: yes
  gather_facts: no 
  vars:
    primary_ntpserver: 0.north-america.pool.ntp.org
    secondary_ntpserver: 1.north-america.pool.ntp.org

  tasks:

  - name: install ntp
    apt: name=ntp state=installed update_cache=yes

  - name: write our ntp.conf
    template: src=/home/ubuntu/files/ntp.conf.j2 dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntp

  - name: start ntp
    service: name=ntp state=started

  handlers:

  - name: restart ntp
    service: name=ntp state=restarted
