---
- hosts: all
  become: yes
  gather_facts: no

  tasks:

  - name: install ntp
    apt: name={{item}} state=installed update_cache=yes
    with_items:
       - ntp
       - ntpdate


  - name: write our ntp.conf
    copy: src=/home/ubuntu/files/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: 
      - restart ntp
      - force ntp update

  - name: start ntp
    service: name=ntp state=started

  handlers:

  - name: restart ntp
    service: name=ntp state=restarted

  - name: force ntp update
    shell: "service ntp stop && ntpdate -s 0.north-america.pool.ntp.org && service ntp start"
