# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define :centos do |centos_config|
    centos_config.vm.box = "centos/7"
    centos_config.vm.hostname = "centos7"
  # centos_config.vm.network :private_network, ip: "10.0.15.12"
  # centos_config.vm.network "forwarded_port", guest: 8080, host: 8888
      centos_config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
      end
    # Enable provisioning with a shell script. Additional provisioners such as
    # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
    # documentation for more information about their specific syntax and use.
     centos_config.vm.provision "shell", inline: <<-SHELL
       yum update -y
       #yum install bind-utils vim nano curl wget telnet ntpdate -y
       yum install bind-utils vim nano curl wget telnet -y
       timedatectl set-timezone America/Los_Angeles
       #ntpdate 0.north-america.pool.ntp.org      
     SHELL
  end
end
